### ISSUE TITLE
Copper pickaxe not mining iron ore

### ISSUE THREAD

**Issue by Giubbottoman** [nice-john/BetterBeginnings_1.0_Forge1.20.1#1]
I installed Better Beginnings mod in my modpack and enjoyed a lot the features it adds. The problem arrived when I first mined the iron ore and it gave me nothing, not even a message saying I need another kind of tool. Of all the mods I have I think the issue is with Spelunkery, since is the only one changing some of the drops given by ores.
I'll do some tests and see if I find out more about the issue.

**Comment by nice-john** [comment]
i think that was because of an error on my part. I accidently put "iron_ore" in the "needs_iron_tool" tag, try the latest version it should work, lmk if it does or doesnt

**Comment by Giubbottoman** [comment]
I updated it, now it works nicely. Great job with the mod anyways.
